import type { FormSchema } from "../types/schema";
import { personasFisicasCoords as C } from "./coordinates/personasFisicas.coords";
import personasFisicasPdf from "../assets/templates/personas-fisicas.pdf?url";

export const personasFisicasSchema: FormSchema = {
  id: "personas-fisicas",
  title: "Identificación de Personas Físicas",
  shortDescription: "Complete sus datos personales, laborales y declaración jurada.",
  templateAsset: personasFisicasPdf,
  pdfStrategy: "acroform",
  sections: [
    {
      id: "datos-personales",
      title: "Datos Personales",
      fields: [
        {
          name: "nombres",
          label: "Nombres y Apellidos",
          type: "text",
          rules: [{ type: "required", message: "Ingrese sus nombres y apellidos" }],
          acroField: "Nombres y Apellidos",
          acroMaxWidth: 308,
        },
        {
          name: "lugarNacimiento",
          label: "Lugar de Nacimiento",
          type: "text",
          rules: [{ type: "required", message: "Ingrese el lugar de nacimiento" }],
          acroField: "Lugar de Nacimiento",
          acroMaxWidth: 97,
        },
        {
          name: "fechaNacimiento",
          label: "Fecha de Nacimiento",
          type: "date",
          rules: [{ type: "required", message: "Ingrese la fecha de nacimiento" }],
          acroField: "Fecha de Nacimiento",
          acroMaxWidth: 88,
        },
        {
          name: "nacionalidad",
          label: "Nacionalidad",
          type: "text",
          rules: [{ type: "required", message: "Ingrese la nacionalidad" }],
          acroField: "Nacionalidad",
          acroMaxWidth: 97,
        },
        {
          name: "ciPasaporte",
          label: "Nº C.I. / Pasaporte",
          type: "text",
          rules: [
            { type: "required", message: "Ingrese el número de C.I. o Pasaporte" },
            { type: "ci", message: "Ingrese un número de C.I. válido" },
          ],
          acroField: "N CI Pasaporte",
          acroMaxWidth: 88,
        },
        {
          name: "estadoCivil",
          label: "Estado civil",
          type: "select",
          options: [
            { value: "soltero", label: "Soltero/a" },
            { value: "casado", label: "Casado/a" },
            { value: "union-de-hecho", label: "Unión de hecho" },
            { value: "divorciado", label: "Divorciado/a" },
            { value: "viudo", label: "Viudo/a" },
          ],
          rules: [{ type: "required", message: "Seleccione el estado civil" }],
          acroField: "Estado civil",
          acroMaxWidth: 97,
        },
        {
          name: "ruc",
          label: "RUC",
          type: "text",
          rules: [{ type: "ruc", message: "Ingrese un RUC válido" }],
          acroField: "RUC",
          acroMaxWidth: 130,
        },
        {
          name: "domicilio",
          label: "Domicilio",
          type: "text",
          rules: [{ type: "required", message: "Ingrese el domicilio" }],
          acroField: "Domicilio",
          acroMaxWidth: 308,
        },
        {
          name: "ciudad",
          label: "Ciudad",
          type: "text",
          rules: [{ type: "required", message: "Ingrese la ciudad" }],
          acroField: "Ciudad",
          acroMaxWidth: 83,
        },
        { name: "telefono", label: "Teléfono", type: "phone", acroField: "Teléfono", acroMaxWidth: 48 },
        {
          name: "celular",
          label: "Celular",
          type: "phone",
          rules: [{ type: "required", message: "Ingrese un número de celular" }],
          acroField: "Celular",
          acroMaxWidth: 60,
        },
        {
          name: "correoElectronico",
          label: "Correo electrónico",
          type: "email",
          rules: [
            { type: "required", message: "Ingrese un correo electrónico" },
            { type: "email", message: "Ingrese un correo electrónico válido" },
          ],
          acroField: "Correo electrónico",
          acroMaxWidth: 308,
        },
        {
          name: "nombreConyuge",
          label: "Nombre del cónyuge",
          type: "text",
          acroField: "Nombre del cónyuge",
          acroMaxWidth: 308,
        },
        {
          name: "esProveedorEstado",
          label: "¿Es proveedor del Estado Paraguayo de algún bien o servicio?",
          type: "radio-yesno",
          rules: [{ type: "required", message: "Seleccione una opción" }],
          pdf: C.esProveedorEstado,
        },
      ],
    },
    {
      id: "datos-laborales",
      title: "Datos Laborales",
      fields: [
        {
          name: "ocupacion",
          label: "Ocupación, oficio o profesión",
          type: "text",
          acroField: "Ocupación oficio o profesión",
          acroMaxWidth: 283,
        },
        {
          name: "empresaEmpleador",
          label: "Empresa y/o Empleador",
          type: "text",
          acroField: "Empresa yo Empleador",
          acroMaxWidth: 283,
        },
        {
          name: "actividadEmpresa",
          label: "Actividad de la Empresa",
          type: "text",
          acroField: "Actividad de la Empresa",
          acroMaxWidth: 283,
        },
        { name: "cargoOcupa", label: "Cargo que ocupa", type: "text", acroField: "Cargo que ocupa", acroMaxWidth: 283 },
        {
          name: "direccionLaboral",
          label: "Dirección laboral",
          type: "text",
          acroField: "Dirección laboral",
          acroMaxWidth: 283,
        },
        { name: "ciudadLaboral", label: "Ciudad", type: "text", acroField: "Ciudad_2", acroMaxWidth: 76 },
        { name: "telefonoLaboral", label: "Teléfono", type: "phone", acroField: "Teléfono_2", acroMaxWidth: 148 },
        {
          name: "correoElectronicoLaboral",
          label: "Correo electrónico",
          type: "email",
          rules: [{ type: "email", message: "Ingrese un correo electrónico válido" }],
          acroField: "Correo electrónico_2",
          acroMaxWidth: 283,
        },
      ],
    },
    {
      id: "declaracion-jurada",
      title: "Declaración Jurada",
      fields: [
        {
          name: "textoDeclaracionJurada",
          label: "Declaración Jurada",
          type: "static-legal-text",
          staticText:
            'En cumplimiento en lo dispuesto por la Ley Nº 1.015/97 que "Previene y Reprime los actos ilícitos destinados a la legitimación de dinero o bienes" y su modificatoria Ley Nº 3783/09, Resol. Nº 071/19 de la Secretaria de Prevención de Lavado de Dinero o Bienes (SEPRELAD).\n\nDeclaro bajo fe de juramento que los fondos con los que opero provienen de actividades lícitas, y que los datos consignados en el presente formulario son correctos y veraces.',
        },
        {
          name: "esFuncionarioPublico",
          label:
            "¿Ocupa o ha ocupado un puesto/cargo público o político (nacional o extranjero) en los últimos 2 (dos) años?",
          type: "radio-yesno",
          rules: [{ type: "required", message: "Seleccione una opción" }],
          pdf: C.esFuncionarioPublico,
        },
        {
          name: "cargo",
          label: "Cargo",
          type: "text",
          showIf: { field: "esFuncionarioPublico", equals: true },
          rules: [{ type: "required", message: "Indique el cargo" }],
          // No acroField: this and "institución" share the template's single blank line
          // ("Texto2") — combined and written there together, see fillAcroFormPdf.ts.
        },
        {
          name: "institucion",
          label: "Institución o ente",
          type: "text",
          showIf: { field: "esFuncionarioPublico", equals: true },
          rules: [{ type: "required", message: "Indique la institución o ente" }],
        },
        {
          name: "fecha",
          label: "Fecha",
          type: "date",
          rules: [{ type: "required", message: "Ingrese la fecha" }],
          acroField: "Fecha",
          acroMaxWidth: 60,
        },
        {
          name: "firma",
          label: "Firma",
          type: "signature",
          // Optional on purpose: the user may prefer to print the PDF and sign on paper,
          // or open it in Adobe to apply a certified digital signature instead.
          pdf: C.firma,
        },
        {
          name: "aclaracion",
          label: "Aclaración",
          type: "text",
          rules: [{ type: "required", message: "Ingrese el nombre en aclaración" }],
          acroField: "Aclaración",
          acroMaxWidth: 66,
        },
      ],
    },
  ],
};
