import type { FormSchema, SelectOption } from "../types/schema";

const SI_NO_OPTIONS: SelectOption[] = [
  { value: "si", label: "Sí" },
  { value: "no", label: "No" },
];

// Matches the official "La Rural" inspection form's damage-grid columns (FR/TR/LI/LD).
const DAMAGE_OPTIONS: SelectOption[] = [
  { value: "abollado", label: "Abollado" },
  { value: "roto", label: "Roto" },
  { value: "desgastado", label: "Desgastado" },
  { value: "pelado", label: "Pelado" },
  { value: "rayado", label: "Rayado" },
  { value: "noTiene", label: "No Tiene" },
];

const ESTADO_GENERAL_OPTIONS: SelectOption[] = [
  { value: "excelente", label: "Excelente" },
  { value: "bueno", label: "Bueno" },
  { value: "regular", label: "Regular" },
  { value: "malo", label: "Malo" },
];

const DIVISION_OPTIONS: SelectOption[] = [
  { value: "agentes", label: "Agentes" },
  { value: "corporativos", label: "Corporativos" },
  { value: "renovaciones", label: "Renovaciones" },
  { value: "regionales", label: "Regionales" },
];

export const revisionAutomovilSchema: FormSchema = {
  id: "revision-automovil",
  title: "Inspección de Riesgo - Sección Automóviles",
  shortDescription: "Inspeccione el estado del vehículo del asegurado, con checklist de condición general y fotos.",
  pdfStrategy: "generated",
  sections: [
    {
      id: "datos-asegurado",
      title: "Datos del Asegurado",
      fields: [
        { name: "nombreAsegurado", label: "Nombre del Asegurado", type: "text", rules: [{ type: "required", message: "Ingrese el nombre del asegurado" }] },
        { name: "documentoIdentidad", label: "Documento de Identidad", type: "text", rules: [{ type: "required", message: "Ingrese el documento de identidad" }] },
        { name: "direccion", label: "Dirección", type: "text" },
        { name: "telefono", label: "Teléfono / Celular", type: "phone" },
        { name: "correoElectronico", label: "Correo Electrónico", type: "email", rules: [{ type: "email", message: "Ingrese un correo electrónico válido" }] },
        { name: "nroPoliza", label: "N° de Póliza", type: "text", rules: [{ type: "required", message: "Ingrese el número de póliza" }] },
        { name: "vigenciaDesde", label: "Vigencia de la Póliza — Desde", type: "date", layoutWidth: "half" },
        { name: "vigenciaHasta", label: "Vigencia de la Póliza — Hasta", type: "date", layoutWidth: "half" },
      ],
    },
    {
      id: "datos-vehiculo",
      title: "Datos del Vehículo",
      fields: [
        { name: "marca", label: "Marca", type: "text", layoutWidth: "half", rules: [{ type: "required", message: "Ingrese la marca" }] },
        { name: "modelo", label: "Modelo", type: "text", layoutWidth: "half" },
        { name: "anio", label: "Año", type: "text", layoutWidth: "half" },
        { name: "color", label: "Color", type: "text", layoutWidth: "half" },
        { name: "tipoVehiculo", label: "Tipo de Vehículo", type: "text", layoutWidth: "half" },
        { name: "matricula", label: "Matrícula / Chapa", type: "text", layoutWidth: "half" },
        { name: "vin", label: "N° de Chasis (VIN)", type: "text" },
        { name: "kilometraje", label: "Kilometraje Actual (km)", type: "text", layoutWidth: "half" },
        {
          name: "usoVehiculo",
          label: "Uso del Vehículo",
          type: "select",
          layoutWidth: "half",
          options: [
            { value: "particular", label: "Particular" },
            { value: "comercial", label: "Comercial" },
            { value: "otro", label: "Otro" },
          ],
        },
      ],
    },
    {
      id: "carroceria-frontal",
      title: "3.1.1 Carrocería y Exterior — Frontal (FR)",
      fields: [
        {
          name: "checklistFrontal",
          label: "Parte Frontal (FR)",
          type: "checklist-matrix",
          options: DAMAGE_OPTIONS,
          tableRows: [
            { key: "paragolpeEnvolvente", label: "Paragolpe/Envolvente" },
            { key: "moduraEnvolventeSpoiler", label: "Modura Envolvente - Spoiler" },
            { key: "faroDelanteroDerecho", label: "Faro delantero derecho" },
            { key: "faroDelanteroIzquierdo", label: "Faro delantero izquierdo" },
            { key: "soporteDeFaro", label: "Soporte de Faro" },
            { key: "buscahuellasDerecho", label: "Buscahuellas derecho" },
            { key: "buscahuellasIzquierdo", label: "Buscahuellas izquierdo" },
            { key: "parrilla", label: "Parrilla" },
            { key: "emblema", label: "Emblema" },
            { key: "capot", label: "Capot" },
            { key: "parabrisasFr", label: "Parabrisas FR" },
            { key: "tapaTiraRemolque", label: "Tapa tira remolque" },
            { key: "soportePortaEquipaje", label: "Soporte Porta Equipaje" },
            { key: "portaEquipaje", label: "Porta Equipaje" },
          ],
        },
      ],
    },
    {
      id: "carroceria-trasera",
      title: "3.1.2 Carrocería y Exterior — Trasera (TR)",
      fields: [
        {
          name: "checklistTrasera",
          label: "Parte Trasera (TR)",
          type: "checklist-matrix",
          options: DAMAGE_OPTIONS,
          tableRows: [
            { key: "paragolpeEnvolvente", label: "Paragolpe/Envolvente" },
            { key: "moduraEnvolventeSpoiler", label: "Modura Envolvente - Spoiler" },
            { key: "faroTraseroDerecho", label: "Faro trasero derecho" },
            { key: "faroTraseroIzquierdo", label: "Faro trasero izquierdo" },
            { key: "soporteDeFaro", label: "Soporte de Faro" },
            { key: "ojoDeGatoDerecho", label: "Ojo de gato derecho" },
            { key: "ojoDeGatoIzquierdo", label: "Ojo de gato izquierdo" },
            { key: "tapaValijeraTapaTrasera", label: "Tapa valijera/Tapa trasera" },
            { key: "monogramaEmblema", label: "Monograma/Emblema" },
            { key: "parabrisasLunetaTr", label: "Parabrisas - Luneta TR" },
            { key: "luzDeFreno", label: "Luz de Freno" },
            { key: "antena", label: "Antena" },
            { key: "techo", label: "Techo" },
            { key: "techoSolar", label: "Techo Solar" },
          ],
        },
      ],
    },
    {
      id: "carroceria-lateral-izquierdo",
      title: "3.1.3 Carrocería y Exterior — Lateral Izquierdo (LI)",
      fields: [
        {
          name: "checklistLateralIzquierdo",
          label: "Lateral Izquierdo (LI)",
          type: "checklist-matrix",
          options: DAMAGE_OPTIONS,
          tableRows: [
            { key: "puertaDelantera", label: "Puerta delantera" },
            { key: "vaguetaDePuertaFr", label: "Vagueta de Puerta FR" },
            { key: "cristalPuertaFr", label: "Cristal puerta FR" },
            { key: "cerraduraDePuertaFr", label: "Cerradura de puerta FR" },
            { key: "guardalluviasPuertaFr", label: "Guardalluvias Puerta FR" },
            { key: "retrovisor", label: "Retrovisor" },
            { key: "esquineroPlasticoRetrovisor", label: "Esquinero plástico de retrovisor" },
            { key: "guardabarroDelantero", label: "Guardabarro delantero" },
            { key: "senaleroGuardabarroFr", label: "Señalero Guardabarro FR" },
            { key: "llantasDeportivasTaza", label: "Llantas Deportivas - Taza" },
            { key: "puertaTrasera", label: "Puerta trasera" },
            { key: "vaguetaDePuertaTr", label: "Vagueta de Puerta TR" },
            { key: "cristalPuertaTr", label: "Cristal puerta TR" },
            { key: "cerraduraDePuertaTr", label: "Cerradura de puerta TR" },
            { key: "guardalluviasPuertaTr", label: "Guardalluvias Puerta TR" },
            { key: "guardabarroTrasero", label: "Guardabarro trasero" },
            { key: "travesanoSuperior", label: "Travesaño Superior" },
            { key: "zocalo", label: "Zócalo" },
            { key: "parante", label: "Parante" },
            { key: "carroceria", label: "Carrocería" },
            { key: "tapaTanque", label: "Tapa tanque" },
          ],
        },
      ],
    },
    {
      id: "carroceria-lateral-derecho",
      title: "3.1.4 Carrocería y Exterior — Lateral Derecho (LD)",
      fields: [
        {
          name: "checklistLateralDerecho",
          label: "Lateral Derecho (LD)",
          type: "checklist-matrix",
          options: DAMAGE_OPTIONS,
          tableRows: [
            { key: "puertaDelantera", label: "Puerta delantera" },
            { key: "vaguetaDePuertaFr", label: "Vagueta de Puerta FR" },
            { key: "cristalPuertaFr", label: "Cristal puerta FR" },
            { key: "cerraduraDePuertaFr", label: "Cerradura de puerta FR" },
            { key: "guardalluviasPuertaFr", label: "Guardalluvias Puerta FR" },
            { key: "retrovisor", label: "Retrovisor" },
            { key: "esquineroPlasticoRetrovisor", label: "Esquinero plástico de retrovisor" },
            { key: "guardabarroDelantero", label: "Guardabarro delantero" },
            { key: "senaleroGuardabarroFr", label: "Señalero Guardabarro FR" },
            { key: "llantasDeportivasTaza", label: "Llantas Deportivas - Taza" },
            { key: "puertaTrasera", label: "Puerta trasera" },
            { key: "vaguetaDePuertaTr", label: "Vagueta de Puerta TR" },
            { key: "cristalPuertaTr", label: "Cristal puerta TR" },
            { key: "cerraduraDePuertaTr", label: "Cerradura de puerta TR" },
            { key: "guardalluviasPuertaTr", label: "Guardalluvias Puerta TR" },
            { key: "guardabarroTrasero", label: "Guardabarro trasero" },
            { key: "travesanoSuperior", label: "Travesaño Superior" },
            { key: "zocalo", label: "Zócalo" },
            { key: "parante", label: "Parante" },
            { key: "carroceria", label: "Carrocería" },
          ],
        },
      ],
    },
    {
      id: "accesorios",
      title: "4. Accesorios",
      fields: [
        {
          name: "checklistAccesoriosGrupo1",
          label: "Accesorios",
          type: "checklist-table",
          options: SI_NO_OPTIONS,
          tableRows: [
            { key: "llantasDeportivas", label: "Llantas Deportivas" },
            { key: "tapaDeRueda", label: "Tapa de Rueda" },
            { key: "tiraTrailer", label: "Tira Trailer" },
            { key: "antivuelcos", label: "Antivuelcos" },
            { key: "estribera", label: "Estribera" },
            { key: "portaEquipaje", label: "Porta Equipaje" },
            { key: "defensaTrasera", label: "Defensa Trasera" },
            { key: "defensaFrontal", label: "Defensa Frontal" },
            { key: "protectorCarroceria", label: "Protect. de Carrocería" },
            { key: "carpaMaritima", label: "Carpa Marítima" },
            { key: "polarizado", label: "Polarizado" },
            { key: "auxilio", label: "Auxilio" },
            { key: "sistemaGps", label: "Sist. GPS" },
            { key: "alarmas", label: "Alarmas" },
            { key: "parabrisasDeFabrica", label: "Parabrisas de Fábrica" },
            { key: "rompeRamas", label: "Rompe Ramas" },
            { key: "aireAcondicionado", label: "Aire Acond." },
            { key: "sistemaAudioAmplificacion", label: "Sist. Audio/Amplific." },
            { key: "autoradio", label: "Autoradio" },
            { key: "molinete", label: "Molinete" },
            { key: "lucesAuxBarraLed", label: "Luces Aux./Barra Led" },
            { key: "reflectores", label: "Reflectores" },
            { key: "antenaElectrica", label: "Antena Eléctrica" },
            { key: "gatoHiLift4x4", label: "Gato Hi Lift p/ 4x4" },
          ],
        },
        {
          name: "checklistFuncionamiento",
          label: "Funcionamiento",
          type: "checklist-table",
          options: SI_NO_OPTIONS,
          tableRows: [
            { key: "farosFr", label: "Faros FR" },
            { key: "farosTr", label: "Faros TR" },
            { key: "senalerosLh", label: "Señaleros LH" },
            { key: "senalerosRh", label: "Señaleros RH" },
            { key: "lucesDeFrenos", label: "Luces de Frenos" },
            { key: "sistemaDeSeguridad", label: "Sist. De Seg." },
          ],
        },
        { name: "marcaCubiertas", label: "Marca de Cubiertas", type: "text", layoutWidth: "half" },
        { name: "medidas", label: "Medidas", type: "text", layoutWidth: "half" },
        { name: "marcaBateria", label: "Marca Batería", type: "text", layoutWidth: "half" },
        { name: "capacidadBateria", label: "Capacidad Batería", type: "text", layoutWidth: "half" },
      ],
    },
    {
      id: "observaciones",
      title: "5. Observaciones",
      fields: [
        { name: "observaciones", label: "Observaciones", type: "textarea", maxLength: 600 },
        {
          name: "estadoGeneralVehiculo",
          label: "Estado General del Vehículo",
          type: "select",
          options: ESTADO_GENERAL_OPTIONS,
        },
      ],
    },
    {
      id: "importante",
      title: "6. Importante",
      fields: [
        {
          name: "textoImportante",
          label: "Importante",
          type: "static-legal-text",
          staticText:
            "Todos los daños preexistentes indicados en el informe de inspección y/o visualizados en las fotografías del vehículo serán excluidos de la cobertura de la póliza. En el caso de que los mismos sean reparados, se deberá comunicar a la compañía aseguradora a fin de realizar la Reinspección correspondiente y puedan ser incluidos dentro de las garantías de la póliza.",
        },
        { name: "firmaEntrevistado", label: "Firma del Entrevistado", type: "signature" },
        { name: "aclaracionEntrevistado", label: "Aclaración", type: "text", layoutWidth: "half" },
        { name: "ciEntrevistado", label: "N° de C.I.", type: "text", layoutWidth: "half" },
        { name: "firmaInspector", label: "Firma del Inspector", type: "signature" },
        { name: "aclaracionInspector", label: "Aclaración", type: "text", layoutWidth: "half" },
        { name: "ciInspector", label: "N° de C.I.", type: "text", layoutWidth: "half" },
        {
          name: "solicitadoPorDivision",
          label: "Solicitado por — División",
          type: "select",
          layoutWidth: "half",
          options: DIVISION_OPTIONS,
        },
        { name: "fechaInspeccion", label: "Fecha de Inspección", type: "date", layoutWidth: "half" },
        { name: "lugarInspeccion", label: "Lugar de Inspección", type: "text" },
      ],
    },
    {
      id: "fotografias-vehiculo",
      title: "Fotografías del Vehículo",
      fields: [
        { name: "fotoFrontal", label: "Frontal", type: "photo", photoMax: 1 },
        { name: "fotoFrontalIzquierdo", label: "Frontal Izquierdo", type: "photo", photoMax: 1 },
        { name: "fotoFrontalDerecho", label: "Frontal Derecho", type: "photo", photoMax: 1 },
        { name: "fotoCostadoDerecho", label: "Costado Derecho", type: "photo", photoMax: 1 },
        { name: "fotoCostadoIzquierdo", label: "Costado Izquierdo", type: "photo", photoMax: 1 },
        { name: "fotoAtras", label: "Atrás", type: "photo", photoMax: 1 },
        { name: "fotoAtrasIzquierda", label: "Atrás Izquierda", type: "photo", photoMax: 1 },
        { name: "fotoAtrasDerecha", label: "Atrás Derecha", type: "photo", photoMax: 1 },
        { name: "fotoHabitaculo", label: "Habitáculo (Interior)", type: "photo", photoMax: 1 },
        { name: "fotoTablero", label: "Tablero", type: "photo", photoMax: 1 },
        { name: "fotoAsientoAtras", label: "Asiento de Atrás", type: "photo", photoMax: 1 },
        { name: "fotoValijera", label: "Valijera / Baúl", type: "photo", photoMax: 1 },
        { name: "fotoMotor", label: "Motor", type: "photo", photoMax: 1 },
        { name: "fotoRadio", label: "Radio", type: "photo", photoMax: 1 },
        { name: "fotosDaniosAdicionales", label: "Daños Adicionales", type: "photo", photoMax: 10 },
        { name: "fotoAccesoriosAgregados", label: "Accesorios Agregados por el Dueño", type: "photo", photoMax: 14 },
      ],
    },
  ],
};
